version: "3.9"
services:
  api:
    image: sanketshirke/knovator-api:latest  # Use Docker Hub image
    env_file:
      - ./node/.env
    ports:
      - "3000:3000"
    networks: [app_net]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/health"]
      interval: 30s
      timeout: 5s
      retries: 3

  frontend:
    image: sanketshirke/knovator-react:latest  # Use Docker Hub image
    networks: [app_net]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost"]
      interval: 30s
      timeout: 5s
      retries: 3

  reverse-proxy:
    image: sanketshirke/knovator-nginx:latest  # Use your custom nginx image
    container_name: reverse-proxy
    depends_on: [api, frontend]
    ports:
      - "80:80"
    networks: [app_net]
    restart: unless-stopped

networks:
  app_net:
    driver: bridge

