version: "3.9"
services:
  api:
    build:
      context: ./node
      dockerfile: Dockerfile
    image: knovator/api:latest
    env_file:
      - ./node/.env
    ports:
      - "3000:3000"
    networks: [app_net]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/health"]
      interval: 30s
      timeout: 5s
      retries: 3

  frontend:
    build:
      context: ./react
    image: knovator/frontend:latest
    networks: [app_net]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost"]
      interval: 30s
      timeout: 5s
      retries: 3

  reverse-proxy:
    image: nginx:alpine
    container_name: reverse-proxy
    depends_on: [api, frontend]
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    networks: [app_net]
    restart: unless-stopped

networks:
  app_net:
    driver: bridge
