version: "3.9"
services:
  api:
    image: ${CI_REGISTRY_IMAGE}/api:${APP_VERSION:-latest}
    env_file:
      - ./env/.api.env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/health"]
      interval: 30s
      timeout: 5s
      retries: 3
    networks: [app_net]

  frontend:
    image: ${CI_REGISTRY_IMAGE}/frontend:${APP_VERSION:-latest}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost"]
      interval: 30s
      timeout: 5s
      retries: 3
    networks: [app_net]

  reverse-proxy:
    image: nginx:alpine
    depends_on: [api, frontend]
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    networks: [app_net]

networks:
  app_net:
    driver: bridge
