name: Docker CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Node API
        uses: docker/build-push-action@v4
        with:
          context: ./node
          file: ./node/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/knovator-api:latest

      - name: Build & Push React Frontend
        uses: docker/build-push-action@v4
        with:
          context: ./react
          file: ./react/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/knovator-frontend:latest

      - name: Build & Push Nginx
        uses: docker/build-push-action@v4
        with:
          context: ./nginx
          file: ./nginx/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/knovator-nginx:latest
