name: CI/CD - Build, Push & Deploy Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Login to DockerHub
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. Build & Push Node API
      - name: Build & Push Node API
        uses: docker/build-push-action@v4
        with:
          context: ./node
          file: ./node/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/knovator-api:latest
            ${{ secrets.DOCKER_USERNAME }}/knovator-api:${{ github.sha }}

      # 4. Build & Push React Frontend
      - name: Build & Push React Frontend
        uses: docker/build-push-action@v4
        with:
          context: ./react
          file: ./react/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/knovator-react:latest
            ${{ secrets.DOCKER_USERNAME }}/knovator-react:${{ github.sha }}

      # 5. Build & Push Nginx
      - name: Build & Push Nginx
        uses: docker/build-push-action@v4
        with:
          context: ./nginx
          file: ./nginx/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/knovator-nginx:latest
            ${{ secrets.DOCKER_USERNAME }}/knovator-nginx:${{ github.sha }}

      # 6. Deploy containers on the same runner
      - name: Deploy containers
        run: |
          docker compose down
          docker compose up -d
